version: '3'

services:
  back:
    build: .
    networks:
      - app
      - db
    depends_on:
      - postgres
  front:
    build: './osau_biblio_front'
    networks:
      - app
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "squadDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "roflrofl1337"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d squadDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5342:5342"
    restart: unless-stopped
    networks:
      - db
networks:
  db:
    driver: bridge
  app:
    driver: bridge
